### ISSUE TITLE
[REQUEST] Merging coord_type into GeneralizedContractionShell

### ISSUE THREAD

**Issue by tovrstra** [theochem/gbasis#113] opened 2020-07-10 16:38 UTC
**Is your feature request related to a problem? Please describe.**

This came up when I was tuning the `from_iodata` function in `gbasis/wrappers.py`. At the moment, this function has two return values: `basis`, which is a list of `GeneralizedContractionShell` instances and `coord_types`, which says for each shell whether it is Cartesian or pure. I would suggest to make the elements of coord_types attributes of the corresponding GeneralizedContractionShell instances. (This can be done in various was effectively, not necessarily literally the way I wrote.)

The motivation for this request is that the `coord_types` part is in practice always tied to the rest of the definition of the basis set. (It is normally not something that is varied during a calculation.) At the moment, when using GBasis, one has to keep track of both variables and pass then into the eval functions every time, which seems redundant and error prone. Forgetting to pass in `coord_types` would essentially always be a bug.

**Is there a specific integral/formula that you would like implemented?**

No

**Is there a change to the code or algorithm you would like to see?**

To be discussed. I can look into options to streamline both variables into one. My first impression is that one could, at the same timel simplify and reduce a lot of the code in the `base*.py` modules.

**Additional context**

None

**Comment by maximilianvz** [comment] 2023-10-24 18:53
I need to leave a comment on this issue in order to be assigned to it by @leila-pujal.

**Comment by leila-pujal** [comment] 2023-11-18 01:33
@maximilianvz  and I have looked at ways to incorporate this change. The `coord_type` variable at the moment is only returned from `from_iodata` but in theory, you can specify the coordinate type for any list of `GeneralizedContractionShell` class objects list. 

Gbasis expects the user to provide information about the coordinate type of a particular shell being defined in cartesian or spherical coordinates. It can either be specified as a whole by just passing "cartesian" or "spherical" strings or shell by shell in a list of strings being either "cartesian" or "spherical". This is a check for I think any evaluation or integral function defined in each module (.py file) to basically sort what kind of contraction_array_* function defined in base_one , base_two and base_four modules to choose.  An example of this for the overlap:
https://github.com/theochem/gbasis/blob/5fcd1904475e7cb0b4c4a0d83c1f980de1b42bf7/gbasis/integrals/overlap.py#L137-L145

Below I explain 2 options that we have thought of: 
-  Delete coord_type from Gbasis API: This would mean we incorporate the coordinate type as an attribute within the `GeneralizedContractionShell` class as @tovrstra suggested. The problem is that now the code showed above doesn’t work for mixed basis containing cartesian and spherical shells. This checked that if a list of strings is passed (the only way to specify mix basis), then it chooses to call the `construct_array_mix` method. You cannot loop over the shells to check the coord type at the same time you are calling the `construct_array_mix`  method because this expects the whole list of contractions because basically this for loop over the shells is done there. You could do a for loop to gather all coord type for each shell and then call the appropriate method. This would be option number 1. (Note: This will work for `from_iodata` and `from_pyscf` wrapper functions. My guess is that it should work for the parsers too since they don’t even return this but me and Max should double-check if changes have to be made). 

- Add an extra type called ‘mix’: This would involve still incorporating a new attribute in the `GeneralizedContractionShell` base class but for this, we will keep the coord_type argument in the API of the functions and the user should know its basis is a mix one. This would require the user to have some knowledge about their basis. This would be option 2.

So far these are the options we came up with. Let us know what you think about it or if you have another suggestions. I will modify this message if I think about an alternative option.

**Comment by PaulWAyers** [comment] 2023-11-18 14:30
I don't see a big advantage to either pathway. I think from the user-facing side it might be easier for users to go with option 1.

From our standpoint, is one much easier than the other? If no one has a strong preference, it might be worth going with the easier one to implement, just so we don't get bogged down.

**Comment by leila-pujal** [comment] 2023-11-21 18:47
@PaulWAyers, I agree I think option 1 is the best option. If we merge the attribute into the class it would be best for this to improve/make easier the API for the more inexperienced user. From the coding part, I think both are the same level of work/difficulty to implement.

**Comment by leila-pujal** [comment] 2023-11-21 18:54
@maximilianvz is currently working on option 1. He should have a draft soon to create a new PR.

**Comment by FarnazH** [comment] 2024-01-11 20:52
See PR #140.

**Closed as completed by FarnazH** 2024-01-11 20:52 UTC
Labels: enhancement
